{% set name = "gc-meox-tms" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install .

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - rdkit

test:
  imports:
    - gc_meox_tms

about:
  home: https://github.com/RECETOX/{{ name }}
  license: MIT
  summary: In-silico MeOX/TMS derivatization of chemical compounds
  description: This package performs in-silico methoximation (MeOX) and trimethylation (TMS) of chemical compounds
    from SMILES strings or RDKit molecule objects. It also can identify whether a given compound is already derivatized
    by MeOX or TMS method.
  dev_url: https://github.com/RECETOX/{{ name }}

extra:
    recipe-maintainers:
      - RECETOX/conda
      - hechth
      - maximskorik